[tool.poetry]
name = "tdd"
version = "0.1.0"
description = ""
authors = ["lucas-placido <lucas.cplacido@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.11"
pytest = "^8.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
